### ISSUE TITLE
Should privacy.firstparty.isolate be set to false? (111.0)

### ISSUE THREAD

**Issue by DKB-91** [Divested-Mobile/Mull-Fenix#124]
From my understanding and Mozilla's release notes, with 111.0 Total Cookie Protection / dFPI has been introduced to Android as well when set to strict, so shouldn't Mull disable it and point user to change settings to strict alongside installing uBlock?

Or is there some difference with the Android version vs the Desktop I'm not aware of that makes FPI still worth it?

**Comment by SkewedZeppelin** [comment]
ETP strict is already default in Mull.

As of 110 at least TCP was still in staged rollout, meaning even if it was flipped on via Nimbus on their end Mull wouldn't have it since it disables that.

I need to check if that is the same on 111 or just patch it always on and switch off FPI.

**Comment by welkinpc-91** [comment]
For the time I'm not going to change anything and wait for confirmation / next update, as browsers aren't my specialty (Firefox less so since I was a Chrome/Spyware user since 2021), I'll just wait on your final word.
From what I can tell the settings in about:config imply both are in place (witj dFPI due to arkenfox carryover peraphs?), but I have no idea if the code for TCP is present.
