### ISSUE TITLE
Fission 

### ISSUE THREAD

**Issue by Striker789** [Divested-Mobile/Mull-Fenix#221]
@SkewedZeppelin Would it be possible to make use of the fission site isolation by giving the user opt-in functionality  (as it has been disabled) to benefit from the security despite of the presence of the bugs? 

Thank you

**Comment by SkewedZeppelin** [comment]
The user can already turn on the fission flags and get process isolation.

But it cannot be disabled afterwards and it is synced with a locked pref that can't only go one way.

**Comment by Striker789** [comment]
@SkewedZeppelin thank you for your response. 

I have enabled `fission.autostart` and `gfx.webrender.all`, however upon viewing `about:support` it states that 0/0 fission windows are enabled by user. Additionally, when viewing `about:processes` , it indicates that there is no isolation between sites. I am currently running the latest version of mull. 

In order to make sure that the steps taken were correct, I had re-run the above steps on Firefox nightly and all sites were isolated after reviewing the `about` commands stated above. 

If there is anything I am missing please do inform me. 

Thank you.

**Comment by SkewedZeppelin** [comment]
Have you had this same install of Mull for a long while?

I did ship a build with Fission enabled briefly before realizing how broken it was. So I added a config change that forced the setting, which is possible to still have persisted despite it no longer being there.

Either that or maybe Mozilla has made it harder to enable on Fenix.
I have not tested it recently due to just how many issues they have left to resolve: https://bugzilla.mozilla.org/show_bug.cgi?id=1610822
