### ISSUE TITLE
add extensions recommended by ffprofile.com

### ISSUE THREAD

**Issue by Nidrop** [Divested-Mobile/Mull-Fenix#23]
[CanvasBlocker](https://addons.mozilla.org/ru/firefox/addon/canvasblocker/) - blocks not only canvas from fingerprinting but also covers webGL, audio, history, window (disabled by default), DOMRect, TextMetrics, navigator (disabled by default) and screen APIs.
[Firefox Multi-Account Containers](https://addons.mozilla.org/ru/firefox/addon/multi-account-containers/) - **Official** addon which allow you to create containers for specific websites.
[Temporary Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/) - Allows you to open tabs, websites, and links in automatically managed disposable containers.
[Cookie AutoDelete](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/) - allows you to automatically delete the cookies of a site when you close the tab.
[ClearURLs](https://addons.mozilla.org/ru/firefox/addon/clearurls/) - Removes tracking elements from URLs.

**Comment by SkewedZeppelin** [comment]
No!

I only recommend uBlock Origin.

**Comment by rustforfuture** [comment]
Also see these:

https://github.com/Divested-Mobile/Mull-Fenix/issues/6#issuecomment-1003768244

For ClearURLs and such addons that you can already use ublock origin for those purposes.

And this:
https://github.com/Divested-Mobile/Mull-Fenix/issues/6#issuecomment-1003782510

Also convas blocker already mitigated by resist fingerprinting flag that mull already have it enabled.

And auto cookie remover, temporary container and such are already mitigated by firstparty isolation and total cookie protection that mull already have.

(And Firefox mobile also already have total cookie protection if you enable strict tracking Protection)

Although other this protections can get achieved by modifying about:config in Firefox for android beta, Firefox for android nightly, and Fennec F-Droid, mull is great because it already have all needed flags enabled by default.

**Comment by rustforfuture** [comment]
> [CanvasBlocker](https://addons.mozilla.org/ru/firefox/addon/canvasblocker/) - blocks not only canvas from fingerprinting but also covers webGL, audio, history, window (disabled by default), DOMRect, TextMetrics, navigator (disabled by default) and screen APIs. [Firefox Multi-Account Containers](https://addons.mozilla.org/ru/firefox/addon/multi-account-containers/) - **Official** addon which allow you to create containers for specific websites. [Temporary Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/) - Allows you to open tabs, websites, and links in automatically managed disposable containers. [Cookie AutoDelete](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/) - allows you to automatically delete the cookies of a site when you close the tab. [ClearURLs](https://addons.mozilla.org/ru/firefox/addon/clearurls/) - Removes tracking elements from URLs.

Also see these:
https://github.com/Divested-Mobile/Mull-Fenix/issues/6#issuecomment-1003768244

For ClearURLs and such addons you can already use ublock origin for those purposes.

And this:
https://github.com/Divested-Mobile/Mull-Fenix/issues/6#issuecomment-1003782510

Also convas blocker already mitigated by resist fingerprinting flag that mull already have it enabled.

And auto cookie remover, temporary container and such are already mitigated by firstparty isolation and total cookie protection that mull already have.

(And Firefox mobile also already have total cookie protection if you enable strict tracking Protection)

Although other this protections can get achieved by modifying about:config in Firefox for android beta, Firefox for android nightly, and Fennec F-Droid, mull is great because it already have all needed flags enabled by default.
