### ISSUE TITLE
98.1.1 not on FDroid yet

### ISSUE THREAD

**Issue by m0rpheas** [Divested-Mobile/Mull-Fenix#44]
Looking on the commit history on Gitlab I noticed there was a new release with 4 critical security fixes. I wanted to report that it is not on FDroid.  Official repo still lists 98.1.0, tried looking in the DivestOS repo too.

**Comment by SkewedZeppelin** [comment]
The latest version is always available on my repo very quickly.
Arguably pre-release... I released 98.1.1 when Mozilla pushed 97.3.0 to Play,
and 98.1.0 6 days before official release date (03/08).

Like all apps on F-Droid, it takes a while, Fenix especially due to the very
long compile time (6+hours per architecture last I checked).

https://divestos.org/misc/ffa-dates.txt
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10691
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10707

**Comment by SkewedZeppelin** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests?scope=all&state=all&author_username=IratePorcupine
https://gitlab.com/relan/fennecbuild/-/merge_requests?scope=all&state=all&author_username=IratePorcupine
