### ISSUE TITLE
about:config not accessible

### ISSUE THREAD

**Issue by bitpixl** [Divested-Mobile/Mull-Fenix#9]
I'm currently trying out this browser and am unable to check out the "about:config" settings to see if arkenfox user.js settings are actually set. On Fennec "about:config" works as intended.

**Comment by SkewedZeppelin** [comment]
You are correct, about:config is indeed inaccessible on 90.1.1.
Will be fixed before release.

**Comment by SkewedZeppelin** [comment]
https://gitlab.com/relan/fennecbuild/-/merge_requests/3

**Comment by SkewedZeppelin** [comment]
New 90.1.1 builds up.
Since currentVersionCode on fdroid wasn't bumped, 90.1.1 wasn't recommended and wouldn't be updated to, I kept the version code on the build unchanged.
If you already have 90.1.1 installed, F-Droid won't let you install it again, so download it here:
- https://divestos.org/fdroid/official/mull-90.1.1-2.android-aarch64.apk
- https://divestos.org/fdroid/official/mull-90.1.1-2.android-arm.apk

**Comment by bitpixl** [comment]
Hi @SkewedZeppelin ,

Appreciate the quick response, keep up the great work 👍

**Comment by neo-neo1** [comment]
I'm using 105.1.0 (from F-Droid) and about:config isn't accessible. Is this intentional?

**Comment by SkewedZeppelin** [comment]
@neo-neo1 
I test about:config every time before release since this event. It should work fine.

Please consider updating to 107.1.0 from my repo. 105.1.0 has 31 known security issues.

**Comment by neo-neo1** [comment]
> 

Sorry for my ignorance, it was an extension blocking it. Are there any precompiled 107.1.0 sources available (reputable which you reocmend)?

**Comment by SkewedZeppelin** [comment]
@neo-neo1 
> precompiled

My official repo: https://divestos.org/index.php?page=our_apps#repos
