### ISSUE TITLE
Wallpapers missing

### ISSUE THREAD

**Issue by ghost** [Divested-Mobile/Mull-Fenix#92]
I'm on 106.1 and when I go to customise wallpaper, only Classic Mull black one is available. On firefox nightly, there are many more

**Comment by towfikomar** [comment]
where is v106?
supposed to updated in 1 week

**Comment by SkewedZeppelin** [comment]
106.1.0 has been on the DivestOS F-Droid repo since for eleven days now: https://divestos.org/misc/ffa-dates.txt
https://divestos.org/index.php?page=our_apps#repos

It is not on the official F-Droid repository because the compile is failing: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11924#note_1145578632

**Comment by libellula** [comment]
I have this same problem on the latest version  (109.2.0).

**Comment by SkewedZeppelin** [comment]
Mozilla made wallpapers work only on official Firefox version: https://gitlab.com/fdroid/fdroiddata/-/issues/2845#note_1258099301

**Comment by sankhababu** [comment]
Sir
Could we get wallpapers as implemented by Fennec f-droid?
It was absent for the time like Mull but back now and different from official FF, WF or Iceraven etc.

**Comment by SkewedZeppelin** [comment]
Wallpapers will not be added because that requires the browser to make more network connections to download them.
